# Generated by Django 3.1.5 on 2021-04-23 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_link_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='image',
            new_name='img',
        ),
    ]
