# Generated by Django 3.1.5 on 2021-05-03 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_link_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='user',
        ),
    ]
