# Generated by Django 3.1.5 on 2021-05-02 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210423_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoría'},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'Sitio'},
        ),
    ]
