# Generated by Django 3.1.5 on 2021-05-02 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210502_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='active',
        ),
    ]
