# Generated by Django 3.1.5 on 2021-05-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20210502_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='link',
        ),
        migrations.AddField(
            model_name='profile',
            name='darkmode',
            field=models.BooleanField(default=False),
        ),
    ]
